// This component is the main (and only) page of your app.
// It renders the full To-Do UI and talks to Supabase to
// load, create, update, and delete tasks.

"use client";

import { useEffect, useState } from "react";
import { supabase } from "../lib/supabaseClient";

// This TypeScript type describes one row from the `todos` table
// in your Supabase database. Keeping it in sync with your DB
// makes it easier to catch mistakes while coding.
type Todo = {
  id: string; // UUID generated by Supabase
  title: string; // Short title of the todo item
  // `description` is an optional, longer piece of text that lets the user
  // add more details about the task. It is optional in the UI, and in the
  // database it is typically stored as a nullable text column.
  description?: string | null;
  is_completed: boolean; // Whether the todo is done or not
  created_at: string; // Timestamp string
};

export default function Home() {
  // `todos` holds the list of tasks currently shown on the page.
  const [todos, setTodos] = useState<Todo[]>([]);

  // `newTitle` holds whatever the user is typing into the title input box.
  const [newTitle, setNewTitle] = useState("");

  // `newDescription` holds the optional extra details for the todo.
  // This is separate from the title so the user can type a short title
  // and a longer explanation if they want to.
  const [newDescription, setNewDescription] = useState("");

  // `isLoading` is true while we are fetching the initial list of todos.
  const [isLoading, setIsLoading] = useState(true);

  // `isSubmitting` is used to prevent double-clicks on the Add button.
  const [isSubmitting, setIsSubmitting] = useState(false);

  // This effect runs once when the component mounts.
  // It loads all existing todos from Supabase so that
  // they appear as soon as the user opens the page.
  useEffect(() => {
    const fetchTodos = async () => {
      // Ask Supabase for all rows in the `todos` table,
      // sorted by `created_at` so older tasks appear first.
      const { data, error } = await supabase
        .from("todos")
        .select("*")
        .order("created_at", { ascending: true });

      if (error) {
        console.error("Error loading todos:", error.message);
        // In a real app you might show a user-friendly toast here.
      } else if (data) {
        setTodos(data as Todo[]);
      }

      setIsLoading(false);
    };

    fetchTodos();
  }, []);

  // Called when the user submits the "Add" form.
  const handleAddTodo = async (event: React.FormEvent) => {
    event.preventDefault(); // Stop the browser from refreshing the page.

    // Trim to remove extra spaces, and avoid inserting empty tasks.
    const trimmedTitle = newTitle.trim();
    if (!trimmedTitle || isSubmitting) return;

    // The description is optional, so we also trim it but we allow it to be
    // empty. When sending to Supabase, we will convert an empty string to
    // `null` so it fits nicely into a nullable text column.
    const trimmedDescription = newDescription.trim();

    setIsSubmitting(true);

    // Insert a new row into the `todos` table.
    const { data, error } = await supabase
      .from("todos")
      .insert({
        title: trimmedTitle,
        // If the user left the description blank, store `null` instead of an
        // empty string so the DB value clearly means “no description”.
        description: trimmedDescription || null,
      }) // `is_completed` will default to false.
      .select()
      .single();

    if (error) {
      console.error("Error adding todo:", error.message);
      // Again, we only log in the console to keep the UI simple for now.
    } else if (data) {
      // We append the new todo to the list so it appears at the bottom.
      setTodos((current) => [...current, data as Todo]);
      setNewTitle(""); // Clear the title input box after adding.
      setNewDescription(""); // Clear the description input box after adding.
    }

    setIsSubmitting(false);
  };

  // Toggle the `is_completed` state for a single todo.
  const handleToggleCompleted = async (todo: Todo) => {
    const { data, error } = await supabase
      .from("todos")
      .update({ is_completed: !todo.is_completed })
      .eq("id", todo.id)
      .select()
      .single();

    if (error) {
      console.error("Error toggling todo:", error.message);
      return;
    }

    if (data) {
      const updated = data as Todo;
      // Replace the old todo in state with the updated one.
      setTodos((current) =>
        current.map((t) => (t.id === updated.id ? updated : t))
      );
    }
  };

  // Completely remove a todo from the database and from state.
  const handleDeleteTodo = async (id: string) => {
    const { error } = await supabase.from("todos").delete().eq("id", id);

    if (error) {
      console.error("Error deleting todo:", error.message);
      return;
    }

    // Filter it out from our local list so the UI updates immediately.
    setTodos((current) => current.filter((t) => t.id !== id));
  };

  return (
    <div className="flex min-h-screen items-center justify-center bg-zinc-100 px-4">
      {/* This main card holds the entire to-do app UI. */}
      <main className="w-full max-w-xl rounded-2xl bg-white p-6 shadow-lg">
        {/* HEADER */}
        <header className="mb-6 text-center">
          <h1 className="text-3xl font-semibold text-zinc-900">
            My To-Do List
          </h1>
          <p className="mt-1 text-sm text-zinc-500">
            A simple Next.js + Supabase app.
          </p>
        </header>

        {/* INPUTS + ADD BUTTON */}
        {/* We wrap the inputs and button in a form so pressing Enter also works. */}
        <form
          onSubmit={handleAddTodo}
          className="mb-6 flex items-start gap-2"
          aria-label="Add a new todo"
        >
          {/* LEFT SIDE: title + optional description stacked vertically. */}
          <div className="flex-1 space-y-2">
            {/* Title input stays as the main required field. */}
            <input
              type="text"
              value={newTitle}
              onChange={(event) => setNewTitle(event.target.value)}
              placeholder="What do you need to do?"
              className="w-full rounded-lg border border-zinc-200 bg-zinc-50 px-3 py-2 text-sm text-zinc-900 outline-none ring-0 transition focus:border-zinc-400 focus:bg-white focus:ring-2 focus:ring-zinc-200"
            />
            {/* New optional description input for extra details. */}
            <textarea
              value={newDescription}
              onChange={(event) => setNewDescription(event.target.value)}
              placeholder="Optional: add a short description or notes"
              className="w-full rounded-lg border border-zinc-200 bg-zinc-50 px-3 py-2 text-xs text-zinc-800 outline-none ring-0 transition focus:border-zinc-400 focus:bg-white focus:ring-2 focus:ring-zinc-200"
              rows={2}
            />
          </div>
          <button
            type="submit"
            disabled={!newTitle.trim() || isSubmitting}
            className="rounded-lg bg-zinc-900 px-4 py-2 text-sm font-medium text-white shadow-sm transition hover:bg-zinc-800 disabled:cursor-not-allowed disabled:bg-zinc-400"
          >
            {isSubmitting ? "Adding..." : "Add"}
          </button>
        </form>

        {/* LIST OF TODOS */}
        <section aria-label="Todo list">
          {isLoading ? (
            // While loading, we show a simple text indicator.
            <p className="text-center text-sm text-zinc-500">
              Loading your tasks...
            </p>
          ) : todos.length === 0 ? (
            // If there are no todos, invite the user to create one.
            <p className="text-center text-sm text-zinc-500">
              You do not have any tasks yet. Add your first one above!
            </p>
          ) : (
            <ul className="space-y-2">
              {todos.map((todo) => (
                <li
                  key={todo.id}
                  className="flex items-center justify-between rounded-lg border border-zinc-200 bg-zinc-50 px-3 py-2"
                >
                  {/* LEFT SIDE: checkbox + title + optional description */}
                  <label className="flex items-start gap-2">
                    <input
                      type="checkbox"
                      checked={todo.is_completed}
                      onChange={() => handleToggleCompleted(todo)}
                      className="h-4 w-4 rounded border-zinc-300 text-zinc-900 focus:ring-zinc-400"
                    />
                    {/* Text block: title on top, description (if present) underneath. */}
                    <div className="flex flex-col">
                      <span
                        className={`text-sm ${
                          todo.is_completed
                            ? "text-zinc-400 line-through"
                            : "text-zinc-900"
                        }`}
                      >
                        {todo.title}
                      </span>
                      {/* Only render the description if the todo actually has one. */}
                      {todo.description && todo.description.trim() && (
                        <p className="mt-0.5 text-xs text-zinc-500">
                          {todo.description}
                        </p>
                      )}
                    </div>
                  </label>

                  {/* RIGHT SIDE: delete button */}
                  <button
                    onClick={() => handleDeleteTodo(todo.id)}
                    className="rounded-md px-2 py-1 text-xs font-medium text-zinc-500 transition hover:bg-red-50 hover:text-red-600"
                    aria-label={`Delete todo: ${todo.title}`}
                  >
                    ✕
                  </button>
                </li>
              ))}
            </ul>
          )}
        </section>
      </main>
    </div>
  );
}

